version: '3'
services:
    bamboo:
        image: linux-devops/bamboo-server:7.0.4
        volumes:
            - bamboo-volume:/var/atlassian/application-data/bamboo
        ports:
            - '54663:54663'
            - '8085:8085'
volumes:
    bamboo-volume:
